### ISSUE TITLE
如何下载data文件下的数据

### ISSUE THREAD

**Issue by cnuzh** [llt1836/TE-HI-GCN#1]
你好，由于数据使用git fls上传到了云端，导致无法下载文章中使用的数据比如pcc_correlation_871_aal_.mat，你能直接将该数据发我邮箱吗？非常感谢

**Comment by llt1836** [comment]
实在不好意思哦，你需要从官网上下载数据然后可以按照github上提供的数据处理方法计算下.mat，因为我没有数据公开权限，所以不能直接发送数据呢。数据下载和处理如果有问题可以再联系我哦。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "llt1836/TE-HI-GCN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月27日(星期六) 中午11:17
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[llt1836/TE-HI-GCN] 如何下载data文件下的数据 (Issue #1)





 
你好，由于数据使用git fls上传到了云端，导致无法下载文章中使用的数据比如pcc_correlation_871_aal_.mat，你能直接将该数据发我邮箱吗？非常感谢
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by cnuzh** [comment]
> 
 哦哦，好的，谢谢你的回复。

**Comment by cnuzh** [comment]
我已经将原始的ABIDE数据集下载下来了，可是按照您的代码并没有生成对应对应的mat文件，使用如下定义的方法，您能在详细描述一下如何生成该文件的吗？
```
raw_data, labels = load_data(data_path, label_path, name)  # raw_data [871 116 ?]  labels [871]
# 划分时间窗
adj = cal_pcc(raw_data)
```

**Comment by llt1836** [comment]
是遇到了什么问题呢

**Comment by cnuzh** [comment]
定义的load_data方法似乎并没有真正读取数据，返回值是空的

**Comment by llt1836** [comment]
这里的逻辑就是读取.1d文件的时序数据，再对照csv文件给数据打上对应的标签。我这里代码是可以使用的呢。

**Comment by cnuzh** [comment]
好的，谢谢啦！
